language: java
env:
  global:
  - CC_TEST_REPORTER_ID=5652c0db4c6b50a85b5ec103eedd3db9ab43c6605e106394bc5f784ed548c4ba
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- mvn test
after_script:
- "./cc-test-reporter format-coverage -d -t jacoco ./target/jacoco-ut/jacoco.xml"
- "./cc-test-reporter upload-coverage -d"
before_deploy:
- mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep
  -v '\[')
deploy:
  provider: releases
  api_key:
    secure: qi/XeqXsgxFxt7HNZ4Zt5QEcBlIO9xJxnWOtOUH1XqJHTt10rL2e3FvVjQ/YPj1wsiRaelBUEBEfxV728Kd/F+NTxLyiajTTm/biDnqwkWAKIIsFdCwvdbE3yMwF4IOdtyv0Foe+Wg1ubkI87zq6QS9vz7vF1gXR7Yo7R23gGZ/YTC+qfvmOY+L1L0Ijl8QeD6ecjaFbEKjUVMc/wAtKIQE8IJt9mwWr5l78YeNd2vbTPF+/zJgULloVafQiFRGGZ+00MtL/7QcBOy5CAUtlAVMFYj/9D9fWdFlogWEqkd3CDAvOLpqdM53sjW+XEzRVD4NDXubMsTIwgiFGLqeskB/m3b6YieTd0cZnQ2qgRj4oD8lLRGqx4OOZCQz1dl2UD1IJUOD484hlSCkWaZs9PB/UOANhwjpCD4eD3l5KrEMfg3vGkYu0x/NTxwAxcQxpnqi3KYTPM5SWvxfIvQc37wr+V4Mnob1UM+Xo7DwY/5vV5CnrioPvFcIfJneS4aDpc4ASPAzM0cgT7mbc/Uflm9Vw7S8EbMyYBpB7ofT3WdGG14iaLdtGCDn4GlRln8Xy6/P8zfeajrSMbRmjNqA41dbLZ/n2wUW7HIXsU5KwaE6i6/keefnLe7OB/+FKexlNRpdLPuCmjVIsWHP9cI9OanbNEH71D60EO/IjqVwT16Y=
  file: ".travis.yml"
  on:
    repo: trickl/clock
