language: java
jdk:
  - openjdk11
env:
  global:
  - CC_TEST_REPORTER_ID=5652c0db4c6b50a85b5ec103eedd3db9ab43c6605e106394bc5f784ed548c4ba
  - secure: uigCiZ16JdvwzTJqUe8YWF4U5gpHpL+whCMhfxDZ1YCSdWw+iOXqzDPZ5BWSXrkLzkSv3OsTCFwFjT1/X/5+vvRPh8ex0NRIN/kMAlstvsX+SJALm6hXur06RVD09L5W3vqcGMbLzowHB5l2KBYzY2p1To2Oi5j+kitk0EvK9wVOb6OIAFiO6dU+I81P6rOFV8CJJlTnoUG3IUgW4Kb3V/URJQ8UKvLi8VIxR81s/q5ghRVxwsQspjoGvqbp9m00FY5ot2p74945aAkI28Aj3oUobIn3epqOrPd/qinpywOO+SwvFfvM8DVqEBE2+Vq5WtFxJTrE7Q0j+4dovLNSZYSWISDKOAVjYBeAAdMIt+N6vUmtpfO8rOHR1B87syMY2DmvpSH4pqxaodfusdzBEZZCPphUQWFDgBb6w+I/ML/NhVpmS5Bf/Rovff+73OChCtIB02cvOwisDU7k98OBoZe5PUX8x92ILBuRqDyII0TK2e2s0WhrQa6oBCqVu1Rm6s3Qpz3yZmnPoXL1Lry/btBGcWmjRvyx3Y5mUm6ljmWdnkh/CwitJh6cloFlRZW37/CbAMyXmnmfBPdfsOQV55l3sxWXTWVa2MrkbUfNi3C7FUUoxLfrZxePhkTNxZrTds4AEA5f3gVC159sBudaC+JhNTTS9i6PgoYip0aavW8=
  - secure: gaHkloqX0GrddzM3MpNneG5Zv7OVozrsHrceJlvxpXLvMv/ME5BoCJ3rzaDjGRNzzidcvoqRO24tpgGAE4QDa7uQkbgly21uAvNnnx9VlDqYh11mKsWifq2ExCOMMF7Ly/jBiybZCwQbiYOYLGYiH1nCWaMZC36DomvlD1l0V03urb+YZYe5hmUEngYcu5CpmCZP1malctFxQ836CkYl0oh+Ztef64J1pHsWJT00bgcNQhpMyMm7Uiw7Ltlsw6O7lU0X/ETcD8w3YELU/ElLx/BVkxVLfTN2p/q7YrBS6pUb67S0paIMR/9ScRuxaPBKu1Pfr0pvOTZI7RQ+SZ7u5kUiAoPMqhEYeBDdd9Dlv3Ij8l4QHklBDnp4XAloNCNNbW3Vbp1tQ7Ifly9Mfp+7zBHR6p8QMR6VsXvu4QGdXoO2wKg8UCiw8DH8TWn+BLN3cdUh9UZZGsCBWHmxMXOUQkPCkN0RUYlj2YLBRzFvPl6xWihucm5fxzpxhcehVSa442vyFcdaFAcnHWDiofxajUYD1deyhjzodre/knR+EQ0c6vpfRS0yiTUm2Ek6XFeTF/IcoObgmC8PGcER2IN5pgDfdyEklIe88vZXaxrVQ679U05CA+1Y9Fegd1qrTaf/NXm8GHEITSMQFBWK/5X5gTX8Vseg90KUR9IJ+IgIUgI=
  - secure: Ynsh7RcSD1si9KZfUEzqFMJsVwrUyMvwvSEENBXxVitgXUoJVbzIPyDQT5L5MJ5c7aTZh0sqg/qlRu3/wk9/74NEEKXNRaTWNoshuODR+TP3lH/FbSjBh094zmIkfe+USyxvzvuVSBCEWJ+/i0keTh2MxIN3CMja9/RqmJc4TLPqiUUWhI6p8Og9D/2IziTIvKOjJZB17/jXN/FbKt16y8loXF8//vxpHvnmjrzYHMYWf9WrLW/cH2TCgv5ulGEmatZAdaKaXpMVXnLW2zFlT42etgSCxrZYbK/CDneNkPouoNGSAETyk+eR+UgO52P37LAYmM2R+QJBzEI4WKUeKUa2gX/ig/KYVaHhy/Np/qnCLxiRVwX3EInl8CgvN6+4tOjm21Q+JcwinC4FcVtONa4UcIlkww2HWFppzZbifkXNT5i61rSwabc6CzQf7/9rcINjugEUxYgAFSl0qsewZRDqepCWWRSrq9TvN/AtktN2DI6QpCBGHXZ7hNFWe4+PZi2BIzlhD75C067qZ+mcz1nxYpfFm/WW7+3qU+4KU6h7GJMP0yy3wXzPx9hJkOwenm5tErIT40x0bS4TYb4Ld+AY4IaV3LBf4Zv/HmmyLqMr6AnQYDjsupw8WB+zgar/uRs2y9za+X4LP5aSTce4CMpB7mLnANpKIeN+dD6+/uo=
install:
- mvn --settings .travis/settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true
  -B -V
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
- ".travis/before-script.sh"
script:
- mvn test
- "./cc-test-reporter format-coverage -d -t jacoco ./target/jacoco-ut/jacoco.xml"
- "./cc-test-reporter upload-coverage -d"
before_deploy:
- mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep
  -v '\[')
deploy:
- provider: script
  script: ".travis/deploy.sh"
  skip_cleanup: true
  on:
    repo: trickl/clock
    all_branches: true
- provider: releases
  skip_cleanup: true
  api_key:
    secure: hwBdwvDgP4HIumCj4kvo3FsVx/wh5DxzHzycgQ8RJ2VByhBJ4fZK6+Z3etg2WzFu43p7wRJn7vNeBzTQeTK51Mrx0CqwYERn3Psg4ySDiTMugz3/7mXsLu0NanfhsBeeVQsDHqigTXTuLL8m1t3fL8iBVKWX2QM8c+04pPFQVCjdEwYqmLO2Y9wy8qEBZd7NgfS83dcSp1FoPosHt628pGI/3yYaL13tuvJDwBOeZSyGr+cEEIYdXbt/qqyd+NRNmGuvyky5Dlnu2rXPFVugx9gdhAnhoO+1LNEUs4wx7r9EG2f5jMyT+pmmev0KXimxvD6H0O4FLk+xB1Jh40eXdtIPF5XWXk9O80Nr4ys2xYxajSGmsnpAdpBXxw02gUsz4+tObamE4CAhKddMXx9URtR+vfG8/dgrGV8nNoPkUX4cnfQ8/e3ocCtvBjziTieZ/FzTvKP0RP2Yy5KaO6SIOKjDSBUFywNVL8+4s94JD4geGIdMFTpZkGRhNgaJMTdp6RDtF1rYBtnd2aKwKUrL1b+wEM0BfmoAGFbsTDfV9dkL1PrX5h3FUScNJF/lBC+VUmNhKqGnNB9UyU6nL7h7BZp2BeBvjJwINXpK7F6Uky+SM8lweq6jqaowBsL5LqH+I410eZXq758LT8cg/AmHPdpiWxSw29izhlKRqeeUPOM=
  file: ".travis.yml"
  on:
    repo: trickl/clock
